# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target '11 - SignUpAnimation' do
pod 'MBSegueCollection', '~> 0.2'
end

