# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target '16 - TumblrMenuReCreation' do
pod 'FontAwesome.swift'
end

target '16 - TumblrMenuReCreationTests' do

end

target '16 - TumblrMenuReCreationUITests' do

end

